### ISSUE TITLE
Problems in ./scprits/configure.sh

### ISSUE THREAD

**Issue by fromWRF** [resibots/blackdrops#15]
I installed the required dependencies by using "./scripts/install_deps_req.sh".
Then, in compilation step, using "./scripts/configure.sh", the problem generated as following:
WARNING: simplejson not found some function may not work 
WARNING: numpy not found 
WARNING: pylab/matplotlib not found 
WARNING: brewer2mpl (colors) not found 
YELLOW: Could not import plot_bo_benchmarks! Will not plot anything! 
WARNING: simplejson not found some function may not work 
Traceback (most recent call last):
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Node.py", line 312, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Scripting.py", line 110, in waf_entry_point
    run_commands()
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Scripting.py", line 167, in run_commands
    parse_options()
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Scripting.py", line 140, in parse_options
    Context.create_context('options').execute()
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/wscript", line 67, in options
    opt.load('compiler_cxx boost waf_unit_test')
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Context.py", line 90, in load
    fun(self)
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Tools/compiler_cxx.py", line 36, in options
    opt.load_special_tools('cxx_*.py')
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Context.py", line 321, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Node.py", line 361, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Node.py", line 361, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration

**Comment by costashatz** [comment]
Hello @fromWRF! Thanks for using our code!

> Traceback (most recent call last):
> File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Node.py", line 312, in ant_iter
> raise StopIteration
> StopIteration

Which OS are you using? I think I know why this is happening.

**Comment by fromWRF** [comment]
> Hello @fromWRF! Thanks for using our code!
> 
> > Traceback (most recent call last):
> > File "/home/wrf/Documents/Temp-robotics_control/blackdrops-master/deps/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Node.py", line 312, in ant_iter
> > raise StopIteration
> > StopIteration
> 
> Which OS are you using? I think I know why this is happening.

Thanks for your reply. I use ubuntu16.04

**Comment by manjusang7** [comment]
Python 3.7 would cause this problem. Use Python 2.7, 3.5, or 3.6.
